[package]
name = "linuxkeys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xdotool = "0.0.2"
evdev = "0.11.4"
once_cell = "1.9.0"